version: "3.3"
services:
  codesets-adapter-db:
    build: ./codesets-adapter-db
    image: codesets-adapter-db
    networks:
      - codesets-adapter-network
    container_name: codesets-adapter-db
    hostname: codesets-adapter-db
    expose:
      - "27017"
    healthcheck:
      test: ["CMD-SHELL", "mongo localhost:27017 --eval db.serverStatus() "]
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - ../../data/codesets-adapter-db/db:/data/db
    env_file:
      - ./codesets-adapter-db/config/db.env
    restart: unless-stopped

  codesets-adapter:
    # build: ./codesets-adapter
    # image: codesets-adapter
    image: nist775hit/hl7-codeset-adapter-prod
    networks:
      - codesets-adapter-network
    expose:
      - "19070"
    ports:
      - "19070:8080"
    container_name: codesets-adapter
    depends_on:
      - codesets-adapter-db
    env_file:
      - ./codesets-adapter-db/config/db.env
    links:
      - codesets-adapter-db:codesets-adapter-db
    volumes:
      - ../../data/codesets-adapter/logs/:/var/log/codesets-adapter/
    restart: unless-stopped

networks:
  codesets-adapter-network:
    name: codesets-adapter-network

